### PR TITLE
feat(charts): removes edc-controlplane and edc-dataplane charts

### PR DESCRIPTION
**Pull request by wolf4ood**
This PR removes the following charts

- `edc-controlplane` 
-  `edc-dataplane` 

We are currently using only the `tractus-connector` one

### CODE REVIEW

**Review by florianrusch-zf — APPROVED** [review]

**Comment by tuncaytunc-zf** [comment]
Maybe removing these charts needs to be aligned with stakeholders, as @DominikPinsel has mentioned here:
https://github.com/eclipse-tractusx/tractusx-edc/issues/167#issuecomment-1490007164

**Comment by florianrusch-zf** [comment]
I think it's not necessary to align this with the "stakeholders" (who ever this is) as we have marked them already as deprecated. Who wants to keep using them needs to take a copy from them and store it somewhere locally 😉

**Review by ndr-brt — APPROVED** [review]
:axe:

**Comment by wolf4ood** [comment]
Hi @SebastianBezold could you merge this? Thanks :)

**Pull request merged**
