### PR TITLE
fix: Adapt Postman collection for 0.3.x

### LINKED ISSUE #228: Adapt Postman collection for v0.3.x
WHAT
The current Postman collection URL are pointing to `/data/` and should be use `/management/` as it is the default setup.
To make it more flexibel the URL prefix like `/management/` should be added to variable definition.

Example variable definition:
`{{PROVIDER_DATAMGMT_URL}}/data/assets` -> `{{PROVIDER_DATAMGMT_URL}}/assets` where `{{PROVIDER_DATAMGMT_URL}}` would look like `<host>:<port>/management`

Add Control Plane Adapter calls to the collection

### PR DESCRIPTION
**Pull request by tuncaytunc-zf**
## WHAT

Adapt Postman collection for version 0.3.x

## WHY

The Postman collection was not compatible with the current version 0.3.x

## FURTHER NOTES

Also the Control Plane Adapter request call is added to the collection.

Closes #228

### CODE REVIEW

**Review by paullatzelsperger — COMMENTED** [review]
If I understood correctly, this collection contains EDC's Management API plus the control plane adapter's API.
However, it's missing our custom Observability API. 

Unifying these things is easy and can be automated, assuming you have EDC checked out in `EDC_DIRECTORY`: 
```bash
# 1. Re-Generate the collective EDC Management API into the TractusX repo
cd <EDC_DIRECTORY>
./gradlew mergeApiSpec --input=resources/openapi/yaml/management-api --output=<TRACTUSX_DIRECTORY>/resources/openapi/yaml/management-api.yaml

# 2. Merge Management API, ControlPlane Adapter API and Observability API
cd <TRACTUSX_DIRECTORY>
./gradlew resolve
./gradlew mergeApiSpec --input=resources/openapi/yaml/ --output=resources/openapi/yaml/txedc-api.yaml
```

Then, in Postman, it is quite easy to import `txedc-api.yaml` into a collection: 
image
After some manual polishing, that collection can be exported using postman.

**Comment by tuncaytunc-zf** [comment]
> If I understood correctly, this collection contains EDC's Management API plus the control plane adapter's API. However, it's missing our custom Observability API.
> 
> Unifying these things is easy and can be automated, assuming you have EDC checked out in `EDC_DIRECTORY`:
> 
> ```shell
> # 1. Re-Generate the collective EDC Management API into the TractusX repo
> cd <EDC_DIRECTORY>
> ./gradlew mergeApiSpec --input=resources/openapi/yaml/management-api --output=<TRACTUSX_DIRECTORY>/resources/openapi/yaml/management-api.yaml
> 
> # 2. Merge Management API, ControlPlane Adapter API and Observability API
> cd <TRACTUSX_DIRECTORY>
> ./gradlew resolve
> ./gradlew mergeApiSpec --input=resources/openapi/yaml/ --output=resources/openapi/yaml/txedc-api.yaml
> ```
> 
> Then, in Postman, it is quite easy to import `txedc-api.yaml` into a collection: image After some manual polishing, that collection can be exported using postman.

As I described in issue, the aim of this is to provide the users a simple collection where they can easily use it to exchange data between two connectors (provider and consumer) with all necessary calls they need. It also provides some variables which are used between several calls and some are initialized automatically after a call. 
It is not about just providing the calls that you would also have by importing the API specification into Postman. I have been contacted multiple times about using/providing such a collection but if we don't want to provide such a collection, of course it can be removed completely since everybody should be able to import the whole api spec into Postman and use the calls that they need.

**Comment by paullatzelsperger** [comment]
that's fine, but I'm assuming users would want the following: 
- the Management API
- the Observability API

which is exactly what the above code snip will produce by merging them into one collection. now, the collection generated by Postman may not be perfect, e.g. it might not yet have tests to store the variables, but IMO that trade-off is worth the benefit of having always-up-to-date collections, that are not error-prone.

In the future we could even automate this in our CI workflows, e.g. using [this app](https://github.com/postmanlabs/OpenAPI-to-Postman).

**Comment by paullatzelsperger** [comment]
if @stephanbcbauer agrees we can merge it as-is

**Review by stephanbcbauer — APPROVED** [review]
Hi @tunacicek @paullatzelsperger ,

Looks good to me. This collection is sufficient (For the "normal user") to test the EDC and retrieve data.

For the future, however, we should think about how to deal with the complete Management API and the Observability API. 

Two further points would be

- the variants in the assets
- and the handling of digital twins. 

I'll create something for this (issue or discussion)

**Pull request merged**
