### PR TITLE
Chore: Remove docusaurus publish workflow

### PR DESCRIPTION
**Pull request by bcronin90**
## WHAT

Removes the workflow for docusaurus docs compilation.

## WHY

Docusaurus docs are no longer tied to this repo.

### CODE REVIEW

**Comment by arnoweiss** [comment]
This file should go as well, right?
https://github.com/bcronin90/tractusx-edc/blob/chore/remove-docusaurus-docs-workflow/resources/create_kit_documentation.sh

**Comment by bcronin90** [comment]
> This file should go as well, right? https://github.com/bcronin90/tractusx-edc/blob/chore/remove-docusaurus-docs-workflow/resources/create_kit_documentation.sh

Good catch, thanks.

**Review by ndr-brt — APPROVED** [review]
please fix conflicts, after then we can merge

**Comment by ndr-brt** [comment]
@bcronin90 could you take care of this PR?

**Review by florianrusch-zf — APPROVED** [review]

**Review by ndr-brt — APPROVED** [review]

**Pull request merged**
