### PR TITLE
Remove lombok from edc tests

### LINKED ISSUE #151: Refactor: remove lombok from `edc-tests`
Remove lombok from the `edc-tests` module

Subtask of #150

### PR DESCRIPTION
**Pull request by wolf4ood**
This PR is the first one of the story #150 lombok for the DR  #143 .

The main target of this pr is the `edc-tests` modules. In particular the `edc-tests:cucumber` one.

## Linked Issue(s)

Closes #151

### CODE REVIEW

**Review by stephanbcbauer — APPROVED** [review]
LGTM so far (haven't tested it)

One question. It seems we are using different formatter. Can we align on one?
=> Discussion for our daily

**Review by ndr-brt — APPROVED** [review]

**Comment by florianrusch-zf** [comment]
> LGTM so far (haven't tested it)
> 
> One question. It seems we are using different formatter. Can we align on one? => Discussion for our daily

We aligned us already. Please have a look here: https://github.com/eclipse-tractusx/tractusx-edc/blob/develop/styleguide.md

PS: I will try to review this PR by end of the day 😉

**Comment by paullatzelsperger** [comment]
@florianrusch-zf can we merge this?

**Comment by florianrusch-zf** [comment]
I hadn't time to look into it. I would trust @wolf4ood @ndr-brt & @stephanbcbauer and our test pipeline and simply hit the merge button 🙈

@paullatzelsperger WDYT?

**Pull request merged**
