### PR TITLE
fix: Issue with sql pool

### PR DESCRIPTION
**Pull request by tuncaytunc-zf**
Fixes the issue with sql pool by adding the missing dependencies.

Fixes the issue: #180

### CODE REVIEW

**Review by wolf4ood — APPROVED** [review]

**Review by florianrusch-zf — APPROVED** [review]

**Comment by florianrusch-zf** [comment]
@tuncaytunc-zf do you know, why this wasn't catched by any tests? Is it even possible to fetch this by any kind of test?

**Comment by matgnt** [comment]
> @tuncaytunc-zf do you know, why this wasn't catched by any tests? Is it even possible to fetch this by any kind of test?

Fully agree. I also wanted to create a few black box tests for the image (which can be only additional tests to what you mentioned) and what limits me is that with the image you have to use azure vault and I can not mock it because of hardcoded domain name in AzureVault.java
```
.vaultUrl("https://" + keyVaultName + ".vault.azure.net")
```
If no security reason is against this, I would propose to make this configurable.

**Comment by tuncaytunc-zf** [comment]
> @tuncaytunc-zf do you know, why this wasn't catched by any tests? Is it even possible to fetch this by any kind of test?

Probably this bug was made by Gradle migration. Unfortunately our tests don't cover so much, in our business-test we just test one image "edc-controlplane-postgresql-hashicorp-vault". This is not the only bug we couldn't catch, there were many others too which could be caught when we would have more tests in place.

**Comment by tuncaytunc-zf** [comment]
Of course we need more tests but starting such a fundamental discussion on such a minor bugfix makes no sense for me. 
We should have had such a discussion before we made a lot of fundamental changes in our code where we fixed them afterwards and still fixing, this is not the only one we have fixed. It seems for me we didn't test our fundamental changes so much. I think we could spend more time on making our products more stable instead of refactoring running/stable code were we introduce a lot of new bugs, since we really don't have so much tests. Instead of implementing new tests we have already started to refactor the existing ones :smiley:

**Review by stefan-ettl — APPROVED** [review]
Hi all, let's focus on the fix first, as Tuncay said.

**Pull request merged**
