### PR TITLE
feat: update DEPENDENCIES, add check to CI

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## WHAT

Updates the `DEPENDENCIES` file, adds a check to the CI that verifies the DEPENDENCIES file is up-to-date

## WHY

compliance with Eclipse

## FURTHER NOTES

- the job will issue a warning if `restricted` dependencies are found
- the job will issue an error and fail if `rejected` dependencies are found
- currently there are still IPLab reviews open: 
  - https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9261
  - https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9262
  - https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9263
  - https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9264
  - https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9265
  - https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9266
  - https://gitlab.eclipse.org/eclipsefdn/emo-team/iplab/-/issues/9267
  
Closes # <-- _insert Issue number if one exists_

### CODE REVIEW

**Review by AngelikaWittek — COMMENTED** [review]
I would recomment to grep over the new dep file for the search-string "rejected" in the status column. A rejected lib means you are not allowed to use it.

**Comment by paullatzelsperger** [comment]
> I would recomment to grep over the new dep file for the search-string "rejected" in the status column. A rejected lib means you are not allowed to use it.

that is a good idea, thanks. in that case we could let the job fail.

**Review by wolf4ood — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
Just to demonstrate how this will look like: 
image

**Comment by Siegfriedk** [comment]
Nice. can you show this in the office hour too? I think we are also planing something very simimliar

**Review by tuncaytunc-zf — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
> Nice. can you show this in the office hour too? I think we are also planing something very simimliar

I had already talked with @SebastianBezold about it. I can definitely share this, but unfortunately i won't be able to make it to the Office Hour on Friday July 7, 2023. Feel free to show it, or I can send out an email to the mailing list.

**Comment by Siegfriedk** [comment]
@paullatzelsperger no worries, there is another Office Hour next Week on the 14th Of July :-)

**Pull request merged**
