### PR TITLE
chore: use new SECURITY.md template

### LINKED ISSUE #888: Outdated `SECURITY.md`
Some time ago, we announced a new template for our `SECURITY.md` file. 
The current one is still using the old template. 
The new one can be found in [sig-security](https://github.com/eclipse-tractusx/sig-security/blob/main/SECURITY.md)

### PR DESCRIPTION
**Pull request by SebastianBezold**
## WHAT

This PR updates the `SECURITY.md` file to follow the most recent template

## WHY

The new template explains usage of GitHub security advisories

## FURTHER NOTES

_List other areas of code that have changed but are not necessarily linked to the main feature. This could be method signature changes, package declarations, bugs that were encountered and were fixed inline, etc._

Closes #888

### CODE REVIEW

**Review by paullatzelsperger — APPROVED** [review]

**Comment by SebastianBezold** [comment]
> Hi @SebastianBezold thanks for the PR,
> 
> seems that the MD linter is complaining [here](https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/7044102155/job/19171127910?pr=891). Once fixed we can merge it
> 
> Thanks

HI @wolf4ood,

oh sorry, missed that. I just took the template that is used everywhere. Do you want me to fix the findings and have a slightly different template formatting?
Changes would be Headline level and proper markdown link instead of bare-URL

**Comment by paullatzelsperger** [comment]
> > Hi @SebastianBezold thanks for the PR,
> > seems that the MD linter is complaining [here](https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/7044102155/job/19171127910?pr=891). Once fixed we can merge it
> > Thanks
> 
> HI @wolf4ood,
> 
> oh sorry, missed that. I just took the template that is used everywhere. Do you want me to fix the findings and have a slightly different template formatting? Changes would be Headline level and proper markdown link instead of bare-URL

@SebastianBezold isn't the markdown linter mandatory in all projects? I mean, wouldn't that formatting issue have surfaced somewhere else too then?

**Comment by SebastianBezold** [comment]
> > > Hi @SebastianBezold thanks for the PR,
> > > seems that the MD linter is complaining [here](https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/7044102155/job/19171127910?pr=891). Once fixed we can merge it
> > > Thanks
> > 
> > 
> > HI @wolf4ood,
> > oh sorry, missed that. I just took the template that is used everywhere. Do you want me to fix the findings and have a slightly different template formatting? Changes would be Headline level and proper markdown link instead of bare-URL
> 
> @SebastianBezold isn't the markdown linter mandatory in all projects? I mean, wouldn't that formatting issue have surfaced somewhere else too then?

Hi @paullatzelsperger,

not that i know?! Don't remember any discussion on the mailing list or a TRG being present for that. 
The only place I know has a markdown linter is the Tractus-X website. This was added, because we have so many different contributors there. But this is also being cheated, since some are adding `.mdx` files and they have been configured to be ignored

**Comment by paullatzelsperger** [comment]
> Hi @paullatzelsperger,
> 
> not that i know?! Don't remember any discussion on the mailing list or a TRG being present for that. The only place I know has a markdown linter is the Tractus-X website. This was added, because we have so many different contributors there. But this is also being cheated, since some are adding `.mdx` files and they have been configured to be ignored

nice. will kick out the linter, and as soon as that is done, you can rebase this PR, which should solve the issues.

**Comment by paullatzelsperger** [comment]
@SebastianBezold i've updated the `SECURITY.md`, as it seems there is some discord as to whether we should kick the linter or not.

**Pull request merged**
