### PR TITLE
fix(helm): Replace deprecated WEB_HTTP_IDS_*

### LINKED ISSUE #875: deprecated WEB_HTTP_IDS_PORT in memory chart
## The deprecated WEB_HTTP_IDS_PORT is still in the "memory" chart

The "memory" chart sets the two environment variables:
WEB_HTTP_IDS_PORT
WEB_HTTP_IDS_PATH

This causes an unreachable /api/v1/dsp endpoint, making the EDC unreachable for other EDCs.

### To Reproduce

Install the "in-memory" chart with default values
Try to query the catalog from another EDC.
image

### Expected behavior

The deployed EDC has a reachable /api/v1/dsp endpoint.

## Context Information
- Used version: 0.5.1 - 0.5.3

## Possible Implementation
Replace
WEB_HTTP_IDS_PORT
WEB_HTTP_IDS_PATH

with
WEB_HTTP_PROTOCOL_PORT
WEB_HTTP_PROTOCOL_PATH

in
https://github.com/eclipse-tractusx/tractusx-edc/blob/main/charts/tractusx-connector-memory/templates/deployment-runtime.yaml

### PR DESCRIPTION
**Pull request by KilianHaag**
## WHAT

Replaces the deprecated WEB_HTTP_IDS_* with WEB_HTTP_PROTOCOL_*

## WHY

see #875

## FURTHER NOTES

Closes #875

### CODE REVIEW

**Comment by wolf4ood** [comment]
Thanks @KilianHaag  for this PR

could you please sign the Eclipse ECA? 

Thanks

**Comment by KilianHaag** [comment]
@wolf4ood I just signed the ECA. How can I retrigger the check?

**Comment by wolf4ood** [comment]
Retriggered still not working, check if the email associated with the commit is the same as the one used in the Eclipse account

**Comment by KilianHaag** [comment]
I double checked. When i click on sign, I can only update the signed ECA.
image


But when I try to "Verify ECA" my email: kilian.haag@t-systems.com is changed to
kilian.haag@t-sy*tems DOT com

image

**Comment by ndr-brt** [comment]
@KilianHaag please ensure that the email address you used to log in the eclipse portal/sign the ECA is the same of the one used to describe the commit

**Comment by KilianHaag** [comment]
@ndr-brt I double checked again:
image

image

I also received the eclipse account registration email on the same mailbox as your GitHub notification.

I even revoked and signed the ECA again,
image
but it seems like I can't retrigger the "Revalidate", as it still says:
image


Is it possible there is something else amiss?

**Comment by KilianHaag** [comment]
@ndr-brt 
In GitHub I had "Keep my email addresses private" set to true.
According to the following issue, this could be the reason.
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/1704

But when checking https://api.eclipse.org/git/eca/status/gh/eclipse-tractusx/tractusx-edc/876? it shows the correct email and not the no-reply version by github.

Could you retrigger the check a final time, otherwise I have no idea, what I can check/change/do on my side.

**Comment by ndr-brt** [comment]
tried to re-validate but nothing happened.
@KilianHaag did you add your github id to you eclipse.org account as suggested in the mentioned issue?
at worst please open an issue on the eclipse helpdesk asking for help.

**Comment by KilianHaag** [comment]
@ndr-brt Yes I checked the username as well.
I now created a helpdesk ticket: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3959

**Comment by KilianHaag** [comment]
@ndr-brt The validation seems to be fixed now: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3959#note_1351746

**Comment by ndr-brt** [comment]
@KilianHaag ok, please fix the `verify-dependencies` check and we'll be ready to go

**Review by ndr-brt — APPROVED** [review]
thanks!

**Pull request merged**
