### PR TITLE
Update management api walkthrough

### PR DESCRIPTION
**Pull request by drandarov-io**
This is a partial update to the [Management API Walkthrough](docs/usage/management-api-walkthrough) with focus on the payloads and consistency.

Not considered for now:
- [01_assets.md](docs/usage/management-api-walkthrough/01_assets.md) > HTTP Data Plane
- [02_policies.md](docs/usage/management-api-walkthrough/02_policies.md) > Testing SSI interactions
- dct namespace changes (https://github.com/eclipse-edc/Connector/pull/3914)
- Callbacks
- EDR resolution

### CODE REVIEW

**Comment by arnoweiss** [comment]
There's currently a different PR (#1241) open that will likely introduce conflicts to the base branch. Since it's more extensive, I'd suggest merging that one first and then adjusting this one.

**Comment by drandarov-io** [comment]
Re-created commit, because commit signature was unverified.

**Comment by wolf4ood** [comment]
@drandarov-io  #1241 has been merged you can rebase and apply your changes 
Thanks

**Comment by arnoweiss** [comment]
Do you intend to add the issues "not considered for now" to this PR? If yes, please convert this back to a draft. If no, this PR covers mostly formatting.

**Comment by drandarov-io** [comment]
I believe PR #1241 covered most of the 0.7.0 changes (like properties being renamed or removed) so for the most part all that is left in the diff is formatting. Therefore, I'd say from my side, the PR ist finished.

**Review by wolf4ood — APPROVED** [review]
LGTM, i would just fix the DEPENDENCIES file.

You can go [here](https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/8751493842/job/24017382133?pr=1242) grab the content between

```
=== Please copy the following content back to DEPENDENCIES ===
...
=== end of content ===
```

and pasted in the `DEPENDENCIES` file and should fix the CI

**Comment by arnoweiss** [comment]
> I believe PR #1241 covered most of the 0.7.0 changes (like properties being renamed or removed) so for the most part all that is left in the diff is formatting. Therefore, I'd say from my side, the PR ist finished.

It would be great if you could quickly go through the files and fix the `http://purl.org/dc/terms` vs `https://purl.org/dc/terms` bug where you find it. Other than that, I think with this and the abovementioned PR, the usage docs appear complete and correct for 0.7.0

**Comment by drandarov-io** [comment]
> > I believe PR #1241 covered most of the 0.7.0 changes (like properties being renamed or removed) so for the most part all that is left in the diff is formatting. Therefore, I'd say from my side, the PR ist finished.
> 
> It would be great if you could quickly go through the files and fix the `http://purl.org/dc/terms` vs `https://purl.org/dc/terms` bug where you find it. Other than that, I think with this and the abovementioned PR, the usage docs appear complete and correct for 0.7.0

I've seen that in the Base Connector Repository they've changed all instances of `https://` to `http://`. Is that what it should be or should the walkthrough use `https://`. I wasn't quite sure of that.

**Pull request merged**
