### PR TITLE
docs: create decision record about migrating from Maven to Gradle

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What

This PR adds a decision-record about migrating the build system from Maven to Gradle

## Why

Every decision must be traceable and transparent

The equivalent PR in `product-edc` has already been approved: https://github.com/catenax-ng/product-edc/pull/795

### CODE REVIEW

**Comment by paullatzelsperger** [comment]
@wolf4ood and @florianrusch-zf could you review this? i cannot request reviews now.

**Comment by SebastianBezold** [comment]
@paullatzelsperger regarding reviews. There is actually the possibility to become an 'official Tractus-X contributor'. That is actually a role, that any committer can assign to anyone else. This will grant you 'Triage' permissions on the org. With triage, you are able to assign issues, label tickets and so on. Also, if i am not mistaken you could see the security issues tab.
Would that be interesting for you?
You can see current contributors already on the EF project page: https://projects.eclipse.org/projects/automotive.tractusx/who

**Comment by paullatzelsperger** [comment]
@SebastianBezold thanks for the detailed explanation. I am currently in the preparatory phase to be elected as a committer on Tractus-X. Is becoming a contributor first necessary?

**Comment by SebastianBezold** [comment]
Hi @paullatzelsperger,
no the contributor step is not a precondition for comitter elections. Could just help out in the meantime. Maybe this is also interesting for some of your colleagues

**Review by florianrusch-zf — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
closing this as the migration to Gradle was done in #115 and #114

**Pull request closed without merging**
