### PR TITLE
Fix/dockerfile windows

### PR DESCRIPTION
**Pull request by mustafasalfiti**
this made it work under windows
but I need a confirmation that this still work under Linux and MacOS as i think it should continue working normally

#853

### CODE REVIEW

**Comment by paullatzelsperger** [comment]
Please see my comment in the associated issue. The docker file is only intended to be used by our internal build process, and I don't see a reason why we should care about windows paths.

**Comment by florianrusch-zf** [comment]
I agree with @paullatzelsperger. Also the change you suggest will break the functionality in all Unix environments.

If you want to make it run on your machine, you can try to use the WSL, which I always recommend when developing on Windows.

**Comment by paullatzelsperger** [comment]
Unrelated: please check out our pr guidelines, as your pr violates many of them

**Comment by mustafasalfiti** [comment]
thank you @florianrusch-zf for your feedback, i can explain exactly what i did in the build.gradle.kts 
I just changed this line buildArgs.put("OTEL_JAR", agentFile.relativeTo(dockerContextDir).path) 
into buildArgs.put("OTEL_JAR", agentFile.relativeTo(dockerContextDir).path.replace("\\", "/"))

so that will change any backslash into forward slash which will cause no problems in the dockerfile.
From my own experience using linux there wont be any backslash in path strings
when the code inside the build.gradle.kts runs under MacOS or Linux we will get a similiar path to
build/ELEMENT.jar

but under windows

build\ELEMENT.jar

so the replace will only change the \ into /

I would be really grateful if you can tell me what do you mean by that and how?
,,Also the change you suggest will break the functionality in all Unix environments"

explaining more will help me to understand

**Comment by mustafasalfiti** [comment]
@paullatzelsperger I think the reason why you should care about windows path and how it should be handled correctly its because windows is the most popular used OS currently.

It can take sometimes hours and days trying to figure out whats wrong and why its not building the projects, so i would prefer that to be written in documentation that its not compatible to be tested and developed under windows because we don't care about it.

it will save us time

thank you for pointing the PR violations i will take it that into consideration for next time.

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger I think the reason why you should care about windows path and how it should be handled correctly its because windows is the most popular used OS currently.
> 
> 
> 
> It can take sometimes hours and days trying to figure out whats wrong and why its not building the projects, so i would prefer that to be written in documentation that its not compatible to be tested and developed under windows because we don't care about it.
> 
> 
> 
> it will save us time
> 
> 
> 
> thank you for pointing the PR violations i will take that into consideration for next time.

Again, the docker file is not intended for public consumption, as the official deliverables are docker images and helm charts. No point in documenting all unsupported scenarios. Users either stick to the supported ones, or they are on their own, as that would be an advanced use case, such as contributing to the project directly.

Advanced users are expected to figure out such basic build principles.

If for some reason you want to build your own docker image of tx-edc, you should create and maintain your own dockerfile instead of relying an internal tx-edc one.

**Pull request closed without merging**
