### PR TITLE
Add parameter for db schema

### LINKED ISSUE #311: Configurable database schema name
**Describe the solution you'd like**

At the time of writing the database schema name, the flyway migration library uses, is not configurable. This means the connector uses the default database schema where it create its tables. Normally this is `public` schema, but might be another schema, too.

There exist deployment environments, where the default schema is not accessible for the EDC and another schema has to be used.

**Additional context** 

As workaround its possible to create a specific database user with a dedicated default schema, the EDC then uses. But a cleaner solution would be a configurable schema name in the EDC itself.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

### PR DESCRIPTION
**Pull request by bcronin90**
## WHAT

Add a parameter to specify the database schema to be used by the postgresql migration extension.

## WHY

As mentioned here: https://github.com/eclipse-tractusx/tractusx-edc/issues/311
Some users might not use the default schema.

## FURTHER NOTES

Could not find documentation of existing parameters, thus did not add this parameter. e2e-tests successful.

Closes #311

Brendan Cronin brendan.cronin@mercedes-benz.com, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)

### CODE REVIEW

**Comment by bcronin90** [comment]
> I'd like a bit of guidance on this. Getting the schema migration to correctly run is no problem. But the tests also use the upstream EDC postgres extension, which afaik doesn't support configuration of a different schema. Any ideas? @DominikPinsel @wolf4ood

Should probably be documented somewhere here:
https://github.com/eclipse-edc/Connector/blob/8e05ee0fb40b59685832ea7032512dbfde6a06ec/extensions/control-plane/store/sql/asset-index-sql/README.md?plain=1#L41

Not sure where else to look.

**Comment by wolf4ood** [comment]
@bcronin90  you should be able to provide the schema with connections parameter in the JDBC url (didn't try it)

https://jdbc.postgresql.org/documentation/use/#connection-parameters

**Comment by bcronin90** [comment]
I'll try that, thanks. ---- On Mi, 07 Jun 2023 12:02:39 +0200  ***@***.***  wrote ----
@bcronin90  you should be able to provide the schema with connections parameter in the JDBC url (didn't try it)
https://jdbc.postgresql.org/documentation/use/#connection-parameters

**Review by wolf4ood — APPROVED** [review]

**Comment by bcronin90** [comment]
@wolf4ood Feel free to merge. I don't have the rights.

**Pull request merged**
