### PR TITLE
fix: pin KICS version to v1.5

### PR DESCRIPTION
**Pull request by paullatzelsperger**
## What
Pins KICS version to 1.5

## Why
Before we were using the `master`, which can break the build because it is not repeatable. We've already seen it break in [product-edc](https://github.com/catenax-ng/product-edc/actions/runs/4421737228/jobs/7752847256)

## Further remarks
Had to upgrade the alpine base image and the openjdk11 JRE version to get rid of the build errors.

### CODE REVIEW

**Comment by wolf4ood** [comment]
LGTM!

**Comment by florianrusch-zf** [comment]
Fine for me. Side note: If we like, we could also pin a specific git sha's instead of a specific version 😉 Dependabot could handle this also already (example: https://github.com/florianrusch/vue3-quagga2/pull/16/files)

As this PR points to the `main` branch, please be aware of the problem I revealed in #112

**Review by florianrusch-zf — APPROVED** [review]

**Review by stefan-ettl — APPROVED** [review]

**Comment by paullatzelsperger** [comment]
build fails because the OpenTelemetry servers are apparently unreachable.

**Comment by paullatzelsperger** [comment]
> As this PR points to the main branch, please be aware of the problem I revealed in https://github.com/eclipse-tractusx/tractusx-edc/issues/112

should i have it target `develop` instead?

**Comment by SebastianBezold** [comment]
Change looks good to me and I'll merge it. I think other teams could have the same issues. Should we align on a general strategy (outside of this issue) about how to keep track of the latest KICS versions?

fyi: @the-tatanka

**Comment by SebastianBezold** [comment]
@paullatzelsperger can you please check, why your tests are failing? Seems like a container build issue:
```
ERROR: unable to select packages:
  openjdk11-jre-headless-11.0.18_p10-r0:
    breaks: world[openjdk11-jre-headless=11.0.17_p8-r3]
```

**Comment by paullatzelsperger** [comment]
> @paullatzelsperger can you please check, why your tests are failing? Seems like a container build issue:
> 
> ```
> ERROR: unable to select packages:
>   openjdk11-jre-headless-11.0.18_p10-r0:
>     breaks: world[openjdk11-jre-headless=11.0.17_p8-r3]
> ```

Could this be a transient error? i restarted CI to make sure

**Comment by paullatzelsperger** [comment]
> Change looks good to me and I'll merge it. I think other teams could have the same issues. Should we align on a general strategy (outside of this issue) about how to keep track of the latest KICS versions?
> 
> fyi: @the-tatanka

Well, one important thing is to always pin versions :)

**Comment by florianrusch-zf** [comment]
> Change looks good to me and I'll merge it. I think other teams could have the same issues. Should we align on a general strategy (outside of this issue) about how to keep track of the latest KICS versions?
> 
> fyi: @the-tatanka

I think if we pined it to a version dependabot will handle this already.

**Comment by florianrusch-zf** [comment]
This PR ist not longer necessary or?

**Comment by the-tatanka** [comment]
> 
> Well, one important thing is to always pin versions :)

In general, I agree.
Working with KICS for years, regarding the action, KICS colleagues often forget the release when there are updates.
Therefore the version on "master", then it is always up to date.
Which as we can see also sometimes leads to problems.

**Comment by paullatzelsperger** [comment]
closing due to #113 and #114

**Pull request closed without merging**
