### PR TITLE
chore(workflows): Add publish-bugfix-release workflow to main

### PR DESCRIPTION
**Pull request by rafaelmag110**
## WHAT

Brings in the temporary publish-bugfix workflow to main from the bugfix/0.7.4 branch.
This is needed for the workflow to be executed manually from the Actions tab.

### CODE REVIEW

**Comment by rafaelmag110** [comment]
@paullatzelsperger @wolf4ood 
Can you review this PR please?

**Comment by paullatzelsperger** [comment]
why do we need this bandaid on `main`? There are plans to "properly" refactor the CI workflows anyway, and there is no urgency at the moment.
Version `0.8.0` is not due for some time.

**Comment by rafaelmag110** [comment]
Github will not identify this workflow exists unless it is on the main branch. For us to run what the bugfix branch has, it has to be here.

We can change the contents and have it do the bare mininum aswell. Like printing "this workflow is not ready on main"...

**Comment by paullatzelsperger** [comment]
> Github will not identify this workflow exists unless it is on the main branch. For us to run what the bugfix branch has, it has to be here.
> 
> We can change the contents and have it do the bare mininum aswell. Like printing "this workflow is not ready on main"...

ah, that's right, forgot about that.

**Review by paullatzelsperger — APPROVED** [review]

**Pull request merged**
